name: Native build
'on':
  - push
jobs:
  ubuntu-latest-build-gcc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: update apt
        run: sudo apt update
      - name: install dependencies
        run: sudo apt install -y gcc g++ libexpat1-dev cmake libbz2-dev zlib1g-dev libomp-dev
      - name: cmake
        run: mkdir build && cd build && cmake ..
      - name: make
        run: cd build && make
      - name: tests
        run: cd build && ctest --output-on-failure
  ubuntu-latest-build-clang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: update apt
        run: sudo apt update
      - name: install dependencies
        run: sudo apt install -y clang libexpat1-dev cmake libbz2-dev zlib1g-dev libomp-dev
      - name: cmake
        run: mkdir build && cd build && cmake ..
        shell: bash
        env:
          CC: clang
          CXX: clang++
      - name: make
        run: cd build && make
      - name: tests
        run: cd build && ctest --output-on-failure
